name: Deploy production vfe exe

on:
  push:
    branches: 
      - main
      
jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
    # Clone src
    - name: Checkout code
      uses: actions/checkout@v2

    # Xóa container nếu đang chạy
    - name: Stop & Remove container
      run: |
        docker stop fe_personal_dictionary || true
        docker rm fe_personal_dictionary || true

    # Xóa image cũ nếu tồn tại
    - name: Delete old image
      run: |
        docker rmi prj || true

    # Build image mới
    - name: Build image
      run: |
        docker build -t exefei .

    # Chạy container mới
    - name: Run container
      run: |
        docker run -d -p 8081:80 --name fe_personal_dictionary prj
